# Auto-Generated by cargo-bitbake 0.3.15
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get meta-rust-test could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/meta-rust-test/0.1.0"
SRC_URI += "git://git@github.com/alex88/meta-rust-test.git;protocol=ssh;nobranch=1"
SRCREV = "fe8a5f15c8b4479f422524ae96184181badf88d8"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""
PV_append = ".AUTOINC+fe8a5f15c8"

# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/actix-rt/2.2.0 \
    crate://crates.io/actix/0.11.1 \
    crate://crates.io/actix_derive/0.6.0 \
    crate://crates.io/aho-corasick/0.7.18 \
    crate://crates.io/async-channel/1.6.1 \
    crate://crates.io/async-executor/1.4.1 \
    crate://crates.io/async-global-executor/2.0.2 \
    crate://crates.io/async-io/1.4.1 \
    crate://crates.io/async-lock/2.4.0 \
    crate://crates.io/async-mutex/1.4.0 \
    crate://crates.io/async-std/1.9.0 \
    crate://crates.io/async-task/4.0.3 \
    crate://crates.io/async-trait/0.1.50 \
    crate://crates.io/atomic-waker/1.0.0 \
    crate://crates.io/atomic/0.5.0 \
    crate://crates.io/atty/0.2.14 \
    crate://crates.io/autocfg/1.0.1 \
    crate://crates.io/base-x/0.2.8 \
    crate://crates.io/binascii/0.1.4 \
    crate://crates.io/bitflags/1.2.1 \
    crate://crates.io/block-buffer/0.7.3 \
    crate://crates.io/block-padding/0.1.5 \
    crate://crates.io/blocking/1.0.2 \
    crate://crates.io/bstr/0.2.16 \
    crate://crates.io/bumpalo/3.6.1 \
    crate://crates.io/byte-tools/0.3.1 \
    crate://crates.io/byteorder/1.4.3 \
    crate://crates.io/bytes/1.0.1 \
    crate://crates.io/cache-padded/1.1.1 \
    crate://crates.io/cc/1.0.68 \
    crate://crates.io/cfg-if/0.1.10 \
    crate://crates.io/cfg-if/1.0.0 \
    crate://crates.io/chrono-tz/0.5.3 \
    crate://crates.io/chrono/0.4.19 \
    crate://crates.io/clap/3.0.0-beta.2 \
    crate://crates.io/clap_derive/3.0.0-beta.2 \
    crate://crates.io/cmake/0.1.45 \
    crate://crates.io/colored/1.9.3 \
    crate://crates.io/concurrent-queue/1.2.2 \
    crate://crates.io/confy/0.4.0 \
    crate://crates.io/const_fn/0.4.8 \
    crate://crates.io/convert_case/0.4.0 \
    crate://crates.io/cookie/0.15.0 \
    crate://crates.io/crossbeam-channel/0.5.1 \
    crate://crates.io/crossbeam-utils/0.8.4 \
    crate://crates.io/ctor/0.1.20 \
    crate://crates.io/derive_more/0.99.14 \
    crate://crates.io/deunicode/0.4.3 \
    crate://crates.io/digest/0.8.1 \
    crate://crates.io/directories/2.0.2 \
    crate://crates.io/dirs-sys/0.3.6 \
    crate://crates.io/discard/1.0.4 \
    crate://crates.io/either/1.6.1 \
    crate://crates.io/encoding_rs/0.8.28 \
    crate://crates.io/event-listener/2.5.1 \
    crate://crates.io/fake-simd/0.1.2 \
    crate://crates.io/fastrand/1.4.1 \
    crate://crates.io/fern/0.5.9 \
    crate://crates.io/figment/0.10.5 \
    crate://crates.io/filetime/0.2.14 \
    crate://crates.io/fnv/1.0.7 \
    crate://crates.io/fsevent-sys/2.0.1 \
    crate://crates.io/fsevent/0.4.0 \
    crate://crates.io/fuchsia-zircon-sys/0.3.3 \
    crate://crates.io/fuchsia-zircon/0.3.3 \
    crate://crates.io/futures-channel/0.3.15 \
    crate://crates.io/futures-core/0.3.15 \
    crate://crates.io/futures-executor/0.3.15 \
    crate://crates.io/futures-io/0.3.15 \
    crate://crates.io/futures-lite/1.11.3 \
    crate://crates.io/futures-macro/0.3.15 \
    crate://crates.io/futures-sink/0.3.15 \
    crate://crates.io/futures-task/0.3.15 \
    crate://crates.io/futures-timer/3.0.2 \
    crate://crates.io/futures-util/0.3.15 \
    crate://crates.io/futures/0.3.15 \
    crate://crates.io/generator/0.6.25 \
    crate://crates.io/generic-array/0.12.4 \
    crate://crates.io/getrandom/0.2.3 \
    crate://crates.io/glob/0.3.0 \
    crate://crates.io/globset/0.4.6 \
    crate://crates.io/globwalk/0.8.1 \
    crate://crates.io/gloo-timers/0.2.1 \
    crate://crates.io/h2/0.3.3 \
    crate://crates.io/hashbrown/0.9.1 \
    crate://crates.io/heck/0.3.2 \
    crate://crates.io/hermit-abi/0.1.18 \
    crate://crates.io/http-body/0.4.2 \
    crate://crates.io/http/0.2.4 \
    crate://crates.io/httparse/1.4.1 \
    crate://crates.io/httpdate/1.0.1 \
    crate://crates.io/humansize/1.1.1 \
    crate://crates.io/hyper/0.14.8 \
    crate://crates.io/ignore/0.4.17 \
    crate://crates.io/indexmap/1.6.2 \
    crate://crates.io/inlinable_string/0.1.14 \
    crate://crates.io/inotify-sys/0.1.5 \
    crate://crates.io/inotify/0.7.1 \
    crate://crates.io/instant/0.1.9 \
    crate://crates.io/iovec/0.1.4 \
    crate://crates.io/ipnetwork/0.18.0 \
    crate://crates.io/itoa/0.4.7 \
    crate://crates.io/js-sys/0.3.51 \
    crate://crates.io/kernel32-sys/0.2.2 \
    crate://crates.io/kv-log-macro/1.0.7 \
    crate://crates.io/lazy_static/1.4.0 \
    crate://crates.io/lazycell/1.3.0 \
    crate://crates.io/libc/0.2.95 \
    crate://crates.io/lock_api/0.4.4 \
    crate://crates.io/log/0.4.14 \
    crate://crates.io/loom/0.3.6 \
    crate://crates.io/maplit/1.0.2 \
    crate://crates.io/memchr/2.4.0 \
    crate://crates.io/mime/0.3.16 \
    crate://crates.io/mio-extras/2.0.6 \
    crate://crates.io/mio/0.6.23 \
    crate://crates.io/mio/0.7.11 \
    crate://crates.io/miow/0.2.2 \
    crate://crates.io/miow/0.3.7 \
    crate://crates.io/multer/2.0.0 \
    crate://crates.io/net2/0.2.37 \
    crate://crates.io/normpath/0.2.0 \
    crate://crates.io/notify/4.0.17 \
    crate://crates.io/ntapi/0.3.6 \
    crate://crates.io/num-integer/0.1.44 \
    crate://crates.io/num-traits/0.2.14 \
    crate://crates.io/num_cpus/1.13.0 \
    crate://crates.io/once_cell/1.7.2 \
    crate://crates.io/opaque-debug/0.2.3 \
    crate://crates.io/openssl-sys/0.9.63 \
    crate://crates.io/os_str_bytes/2.4.0 \
    crate://crates.io/paho-mqtt-sys/0.5.0 \
    crate://crates.io/paho-mqtt/0.9.1 \
    crate://crates.io/parking/2.0.0 \
    crate://crates.io/parking_lot/0.11.1 \
    crate://crates.io/parking_lot_core/0.8.3 \
    crate://crates.io/parse-zoneinfo/0.3.0 \
    crate://crates.io/pear/0.2.3 \
    crate://crates.io/pear_codegen/0.2.3 \
    crate://crates.io/percent-encoding/2.1.0 \
    crate://crates.io/pest/2.1.3 \
    crate://crates.io/pest_derive/2.1.0 \
    crate://crates.io/pest_generator/2.1.3 \
    crate://crates.io/pest_meta/2.1.3 \
    crate://crates.io/pin-project-internal/1.0.7 \
    crate://crates.io/pin-project-lite/0.2.6 \
    crate://crates.io/pin-project/1.0.7 \
    crate://crates.io/pin-utils/0.1.0 \
    crate://crates.io/pkg-config/0.3.19 \
    crate://crates.io/pnet/0.28.0 \
    crate://crates.io/pnet_base/0.28.0 \
    crate://crates.io/pnet_datalink/0.28.0 \
    crate://crates.io/pnet_macros/0.28.0 \
    crate://crates.io/pnet_macros_support/0.28.0 \
    crate://crates.io/pnet_packet/0.28.0 \
    crate://crates.io/pnet_sys/0.28.0 \
    crate://crates.io/pnet_transport/0.28.0 \
    crate://crates.io/polling/2.0.3 \
    crate://crates.io/ppv-lite86/0.2.10 \
    crate://crates.io/proc-macro-error-attr/1.0.4 \
    crate://crates.io/proc-macro-error/1.0.4 \
    crate://crates.io/proc-macro-hack/0.5.19 \
    crate://crates.io/proc-macro-nested/0.1.7 \
    crate://crates.io/proc-macro2-diagnostics/0.9.1 \
    crate://crates.io/proc-macro2/1.0.27 \
    crate://crates.io/quote/1.0.9 \
    crate://crates.io/rand/0.8.3 \
    crate://crates.io/rand_chacha/0.3.0 \
    crate://crates.io/rand_core/0.6.2 \
    crate://crates.io/rand_hc/0.3.0 \
    crate://crates.io/redox_syscall/0.2.8 \
    crate://crates.io/redox_users/0.4.0 \
    crate://crates.io/ref-cast-impl/1.0.6 \
    crate://crates.io/ref-cast/1.0.6 \
    crate://crates.io/regex-syntax/0.6.25 \
    crate://crates.io/regex/1.5.4 \
    crate://crates.io/remove_dir_all/0.5.3 \
    crate://crates.io/rustc_version/0.2.3 \
    crate://crates.io/rustversion/1.0.5 \
    crate://crates.io/ryu/1.0.5 \
    crate://crates.io/same-file/1.0.6 \
    crate://crates.io/scoped-tls/1.0.0 \
    crate://crates.io/scopeguard/1.1.0 \
    crate://crates.io/semver-parser/0.7.0 \
    crate://crates.io/semver/0.9.0 \
    crate://crates.io/serde/1.0.126 \
    crate://crates.io/serde_derive/1.0.126 \
    crate://crates.io/serde_json/1.0.64 \
    crate://crates.io/sha-1/0.8.2 \
    crate://crates.io/sha1/0.6.0 \
    crate://crates.io/signal-hook-registry/1.3.0 \
    crate://crates.io/slab/0.4.3 \
    crate://crates.io/slug/0.1.4 \
    crate://crates.io/smallvec/1.6.1 \
    crate://crates.io/socket2/0.4.0 \
    crate://crates.io/spin/0.9.0 \
    crate://crates.io/stable-pattern/0.1.0 \
    crate://crates.io/standback/0.2.17 \
    crate://crates.io/stdweb-derive/0.5.3 \
    crate://crates.io/stdweb-internal-macros/0.2.9 \
    crate://crates.io/stdweb-internal-runtime/0.1.5 \
    crate://crates.io/stdweb/0.4.20 \
    crate://crates.io/strsim/0.10.0 \
    crate://crates.io/syn/1.0.72 \
    crate://crates.io/tempfile/3.2.0 \
    crate://crates.io/tera/1.10.0 \
    crate://crates.io/termcolor/1.1.2 \
    crate://crates.io/textwrap/0.12.1 \
    crate://crates.io/thiserror-impl/1.0.25 \
    crate://crates.io/thiserror/1.0.25 \
    crate://crates.io/thread_local/1.1.3 \
    crate://crates.io/time-macros-impl/0.1.1 \
    crate://crates.io/time-macros/0.1.1 \
    crate://crates.io/time/0.1.43 \
    crate://crates.io/time/0.2.26 \
    crate://crates.io/tokio-macros/1.2.0 \
    crate://crates.io/tokio-util/0.6.7 \
    crate://crates.io/tokio/1.6.0 \
    crate://crates.io/toml/0.5.8 \
    crate://crates.io/tower-service/0.3.1 \
    crate://crates.io/tracing-core/0.1.18 \
    crate://crates.io/tracing/0.1.26 \
    crate://crates.io/try-lock/0.2.3 \
    crate://crates.io/twoway/0.2.2 \
    crate://crates.io/typenum/1.13.0 \
    crate://crates.io/ubyte/0.10.1 \
    crate://crates.io/ucd-trie/0.1.3 \
    crate://crates.io/uncased/0.9.6 \
    crate://crates.io/unchecked-index/0.2.2 \
    crate://crates.io/unic-char-property/0.9.0 \
    crate://crates.io/unic-char-range/0.9.0 \
    crate://crates.io/unic-common/0.9.0 \
    crate://crates.io/unic-segment/0.9.0 \
    crate://crates.io/unic-ucd-segment/0.9.0 \
    crate://crates.io/unic-ucd-version/0.9.0 \
    crate://crates.io/unicode-segmentation/1.7.1 \
    crate://crates.io/unicode-width/0.1.8 \
    crate://crates.io/unicode-xid/0.2.2 \
    crate://crates.io/value-bag/1.0.0-alpha.7 \
    crate://crates.io/vcpkg/0.2.13 \
    crate://crates.io/vec_map/0.8.2 \
    crate://crates.io/version_check/0.9.3 \
    crate://crates.io/waker-fn/1.1.0 \
    crate://crates.io/walkdir/2.3.2 \
    crate://crates.io/want/0.3.0 \
    crate://crates.io/wasi/0.10.2+wasi-snapshot-preview1 \
    crate://crates.io/wasm-bindgen-backend/0.2.74 \
    crate://crates.io/wasm-bindgen-futures/0.4.24 \
    crate://crates.io/wasm-bindgen-macro-support/0.2.74 \
    crate://crates.io/wasm-bindgen-macro/0.2.74 \
    crate://crates.io/wasm-bindgen-shared/0.2.74 \
    crate://crates.io/wasm-bindgen/0.2.74 \
    crate://crates.io/web-sys/0.3.51 \
    crate://crates.io/wepoll-sys/3.0.1 \
    crate://crates.io/winapi-build/0.1.1 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-util/0.1.5 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi/0.2.8 \
    crate://crates.io/winapi/0.3.9 \
    crate://crates.io/ws2_32-sys/0.2.1 \
    crate://crates.io/yansi/0.5.0 \
    git://github.com/SergioBenitez/Devise.git;protocol=https;nobranch=1;name=devise;destsuffix=devise \
    git://github.com/SergioBenitez/Devise.git;protocol=https;nobranch=1;name=devise_codegen;destsuffix=devise_codegen \
    git://github.com/SergioBenitez/Devise.git;protocol=https;nobranch=1;name=devise_core;destsuffix=devise_core \
    git://github.com/SergioBenitez/Rocket;protocol=https;nobranch=1;name=rocket;destsuffix=rocket \
    git://github.com/SergioBenitez/Rocket;protocol=https;nobranch=1;name=rocket_codegen;destsuffix=rocket_codegen \
    git://github.com/SergioBenitez/Rocket;protocol=https;nobranch=1;name=rocket_contrib;destsuffix=rocket_contrib \
    git://github.com/SergioBenitez/Rocket;protocol=https;nobranch=1;name=rocket_http;destsuffix=rocket_http \
    git://github.com/SergioBenitez/async-stream.git;protocol=https;nobranch=1;name=async-stream-impl;destsuffix=async-stream-impl \
    git://github.com/SergioBenitez/async-stream.git;protocol=https;nobranch=1;name=async-stream;destsuffix=async-stream \
    git://github.com/SergioBenitez/state.git;protocol=https;nobranch=1;name=state;destsuffix=state \
"

SRCREV_FORMAT .= "_async-stream"
SRCREV_async-stream = "c46ada948e0d4800393836f57eb2a3db516beb1e"
EXTRA_OECARGO_PATHS += "${WORKDIR}/async-stream"
SRCREV_FORMAT .= "_async-stream-impl"
SRCREV_async-stream-impl = "c46ada948e0d4800393836f57eb2a3db516beb1e"
EXTRA_OECARGO_PATHS += "${WORKDIR}/async-stream-impl"
SRCREV_FORMAT .= "_devise"
SRCREV_devise = "df00b5162edd53e8d496e7935774e69b5f7f6bdf"
EXTRA_OECARGO_PATHS += "${WORKDIR}/devise"
SRCREV_FORMAT .= "_devise_codegen"
SRCREV_devise_codegen = "df00b5162edd53e8d496e7935774e69b5f7f6bdf"
EXTRA_OECARGO_PATHS += "${WORKDIR}/devise_codegen"
SRCREV_FORMAT .= "_devise_core"
SRCREV_devise_core = "df00b5162edd53e8d496e7935774e69b5f7f6bdf"
EXTRA_OECARGO_PATHS += "${WORKDIR}/devise_core"
SRCREV_FORMAT .= "_rocket"
SRCREV_rocket = "f85604b65ef3d1335adfeb98a0a83be34c27388d"
EXTRA_OECARGO_PATHS += "${WORKDIR}/rocket"
SRCREV_FORMAT .= "_rocket_codegen"
SRCREV_rocket_codegen = "f85604b65ef3d1335adfeb98a0a83be34c27388d"
EXTRA_OECARGO_PATHS += "${WORKDIR}/rocket_codegen"
SRCREV_FORMAT .= "_rocket_contrib"
SRCREV_rocket_contrib = "f85604b65ef3d1335adfeb98a0a83be34c27388d"
EXTRA_OECARGO_PATHS += "${WORKDIR}/rocket_contrib"
SRCREV_FORMAT .= "_rocket_http"
SRCREV_rocket_http = "f85604b65ef3d1335adfeb98a0a83be34c27388d"
EXTRA_OECARGO_PATHS += "${WORKDIR}/rocket_http"
SRCREV_FORMAT .= "_state"
SRCREV_state = "8f94dce673b7d4b0e7b96c808a84f5e2a4be4a60"
EXTRA_OECARGO_PATHS += "${WORKDIR}/state"

# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    "

SUMMARY = "meta-rust-test"
HOMEPAGE = "git@github.com:alex88/meta-rust-test.git"
LICENSE = "CLOSED"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include meta-rust-test-${PV}.inc
include meta-rust-test.inc
